# Generated by Django 4.2 on 2024-03-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_event'),
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='invitee',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='inviter',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='is_accepted',
            new_name='status',
        ),
        migrations.AddField(
            model_name='invitation',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='calendars.calendar'),
        ),
    ]
