# Generated by Django 4.2 on 2024-03-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_event'),
        ('invitations', '0002_rename_invitee_invitation_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='calendars.calendar'),
        ),
    ]
