# Generated by Django 4.2 on 2024-03-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_alter_invitation_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='status',
        ),
        migrations.AddField(
            model_name='invitation',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Accept Invitation'),
        ),
    ]
