# Generated by Django 5.0.3 on 2024-03-28 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "guests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="guest_calendars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hosts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="host_calendars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "super_hosts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="super_host_calendars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
