# Generated by Django 5.0.3 on 2024-03-30 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendar",
            name="super_hosts",
        ),
    ]
