# Generated by Django 4.2 on 2024-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Accept Invitation'),
        ),
    ]
