# Generated by Django 5.0.3 on 2024-03-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_remove_event_attendee_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendee_limit',
        ),
    ]
