# Generated by Django 5.0.3 on 2024-03-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_rename_time_event_start_time_event_calendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
    ]
